
project_id = "oknofqytitpxmlprvekn"

[functions.stripe-webhook]
verify_jwt = false

[functions.get-subscription]
verify_jwt = true

[functions.qbo-authorize]
verify_jwt = true

[functions.qbo-callback]
verify_jwt = false
